version: '3'
services:
  clickhouse:
    build: ./clickhouse-config/
    ports:
      - "9000:9000"
      - "8123:8123"
    logging:
      options:
        max-size: "50m"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    restart: always